env:
  browser: true
  es2020: true
extends:
  - 'plugin:react/recommended'
  - google
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - prettier
rules:
  # 関数の複雑さを 10 以下にする
  complexity: ['error', 10]
  # prettier のチェックでErrorとするための設定
  prettier/prettier:
    - error
